helmCharts:
  - name: ../charts/elasticsearch
    releaseName: elasticsearch
    namespace: efk-stack
    valuesFile: ./elasticsearch-values.yaml
  - name: ../charts/kibana
    releaseName: kibana
    namespace: efk-stack
  - name: ../charts/fluent-bit
    releaseName: fluent-bit
    namespace: efk-stack
